/**
 * Token emitters.
 *
 * Each emitter takes a `Palette` (plus options) and returns a string you can
 * paste or write to disk. They are deliberately plain string builders rather
 * than a templating abstraction: the formats differ enough in structure that a
 * shared template would obscure more than it saved, and readable output matters
 * more here than DRY. This text lands in someone's repo.
 */

import { contrastMatrix } from "../color/contrast.js";
import { formatOklch, fromHex, rgbToOklch } from "../color/convert.js";
import { scale, TONE_STOPS } from "../color/scale.js";
import { deriveTheme, type ThemeOptions } from "../theme.js";
import type { Palette, Swatch, ToneScale } from "../types.js";

export type TokenFormat =
  | "css"
  | "tailwind"
  | "scss"
  | "ts"
  | "js"
  | "json"
  | "dtcg"
  | "shadcn"
  | "svg";

export interface EmitOptions {
  /** Prefix for variable names, e.g. `"brand"` → `--brand-primary`. Default none. */
  prefix?: string;
  /** Emit the full 50 to 950 ramp for each swatch, not just the flat colour. */
  scales?: boolean;
  /** Emit `oklch()` instead of hex where the format supports it. Default `false`. */
  oklch?: boolean;
  /** Options forwarded to `deriveTheme` for the `shadcn` format. */
  theme?: ThemeOptions;
  /** Include a provenance header comment. Default `true`. */
  header?: boolean;
}

const HEADER =
  "Generated by Palette Forge, https://palette-forge-web.vercel.app/";

const withPrefix = (prefix: string | undefined, name: string) =>
  prefix ? `${prefix}-${name}` : name;

const value = (swatch: Swatch, oklch: boolean) =>
  oklch ? formatOklch(swatch.oklch) : swatch.hex;

/** Same choice, for a ramp stop that only exists as a hex string. */
const rampValue = (hex: string, oklch: boolean) =>
  oklch ? formatOklch(rgbToOklch(fromHex(hex))) : hex;

/* ----------------------------------------------------------------- css --- */

/** Plain CSS custom properties on `:root`. */
export function toCSS(palette: Palette, options: EmitOptions = {}): string {
  const { prefix, scales = false, oklch = false, header = true } = options;
  const lines: string[] = [];

  if (header) lines.push(`/* ${HEADER} */`);
  lines.push(":root {");

  for (const swatch of palette.swatches) {
    const name = withPrefix(prefix, swatch.name);
    lines.push(`  --${name}: ${value(swatch, oklch)};`);
  }

  if (scales) {
    for (const swatch of palette.swatches) {
      lines.push("");
      const ramp = rampFor(swatch);
      for (const stop of TONE_STOPS) {
        lines.push(`  --${withPrefix(prefix, swatch.name)}-${stop}: ${ramp[stop]};`);
      }
    }
  }

  lines.push("}");
  return lines.join("\n");
}

/* ------------------------------------------------------------ tailwind --- */

/**
 * Tailwind v4 `@theme` block. Colours are emitted as `oklch()` by default
 * because that is what Tailwind v4's own palette ships as, which keeps
 * interpolation (gradients, opacity modifiers) consistent with the built-ins.
 */
export function toTailwind(palette: Palette, options: EmitOptions = {}): string {
  const { prefix, scales = true, oklch = true, header = true } = options;
  const lines: string[] = [];

  if (header) lines.push(`/* ${HEADER} */`);
  lines.push('@import "tailwindcss";', "", "@theme {");

  for (const swatch of palette.swatches) {
    const name = withPrefix(prefix, swatch.name);
    if (scales) {
      const ramp = rampFor(swatch);
      for (const stop of TONE_STOPS) {
        lines.push(`  --color-${name}-${stop}: ${rampValue(ramp[stop], oklch)};`);
      }
      lines.push(`  --color-${name}: ${value(swatch, oklch)};`);
      lines.push("");
    } else {
      lines.push(`  --color-${name}: ${value(swatch, oklch)};`);
    }
  }

  if (lines.at(-1) === "") lines.pop();
  lines.push("}");
  lines.push("");
  lines.push("/* Use them as any other Tailwind colour: */");
  lines.push(
    `/*   <div class="bg-${withPrefix(prefix, palette.swatches[0]?.name ?? "primary")}${
      scales ? "-500" : ""
    } text-white"> */`,
  );

  return lines.join("\n");
}

/* ---------------------------------------------------------------- scss --- */

export function toSCSS(palette: Palette, options: EmitOptions = {}): string {
  const { prefix, scales = false, oklch = false, header = true } = options;
  const lines: string[] = [];

  if (header) lines.push(`// ${HEADER}`);

  for (const swatch of palette.swatches) {
    lines.push(`$${withPrefix(prefix, swatch.name)}: ${value(swatch, oklch)};`);
  }

  if (scales) {
    lines.push("");
    for (const swatch of palette.swatches) {
      const ramp = rampFor(swatch);
      const entries = TONE_STOPS.map((stop) => `  ${stop}: ${ramp[stop]}`).join(",\n");
      lines.push(`$${withPrefix(prefix, swatch.name)}-scale: (\n${entries}\n);`);
    }
  }

  return lines.join("\n");
}

/* ------------------------------------------------------------ ts / js --- */

export function toTypeScript(palette: Palette, options: EmitOptions = {}): string {
  const { prefix, scales = false, header = true } = options;
  const lines: string[] = [];

  if (header) lines.push(`// ${HEADER}`);

  lines.push("export const palette = {");
  for (const swatch of palette.swatches) {
    lines.push(`  ${quoteKey(withPrefix(prefix, swatch.name))}: ${JSON.stringify(swatch.hex)},`);
  }
  lines.push("} as const;", "");

  if (scales) {
    lines.push("export const scales = {");
    for (const swatch of palette.swatches) {
      const ramp = rampFor(swatch);
      lines.push(`  ${quoteKey(withPrefix(prefix, swatch.name))}: {`);
      for (const stop of TONE_STOPS) {
        lines.push(`    ${stop}: ${JSON.stringify(ramp[stop])},`);
      }
      lines.push("  },");
    }
    lines.push("} as const;", "");
  }

  lines.push("export type PaletteToken = keyof typeof palette;");
  return lines.join("\n");
}

export function toJavaScript(palette: Palette, options: EmitOptions = {}): string {
  return toTypeScript(palette, options)
    .replace(/ as const;/g, ";")
    .replace(/\n?export type PaletteToken.*\n?/g, "");
}

/* ---------------------------------------------------------------- json --- */

/** Rich JSON: every swatch with its measurements and role. */
export function toJSON(palette: Palette, options: EmitOptions = {}): string {
  const { prefix } = options;
  return JSON.stringify(
    {
      $generator: HEADER,
      colors: palette.swatches.map((swatch) => ({
        name: withPrefix(prefix, swatch.name),
        hex: swatch.hex,
        role: swatch.role,
        rgb: swatch.rgb,
        hsl: swatch.hsl,
        oklch: {
          l: +swatch.oklch[0].toFixed(4),
          c: +swatch.oklch[1].toFixed(4),
          h: +swatch.oklch[2].toFixed(2),
        },
        coverage: +(swatch.share * 100).toFixed(2),
        luminance: +swatch.luminance.toFixed(4),
        on: swatch.on,
      })),
      contrast: contrastMatrix(palette.swatches.map((s) => s.hex), { limit: 40 }),
      meta: palette.meta,
    },
    null,
    2,
  );
}

/**
 * W3C Design Tokens Community Group format. The interchange format Style
 * Dictionary, Tokens Studio and Figma Variables all read.
 */
export function toDTCG(palette: Palette, options: EmitOptions = {}): string {
  const { prefix, scales = true } = options;
  const group: Record<string, unknown> = {};

  for (const swatch of palette.swatches) {
    const name = withPrefix(prefix, swatch.name);
    if (scales) {
      const ramp = rampFor(swatch);
      const entries: Record<string, unknown> = {};
      for (const stop of TONE_STOPS) {
        entries[String(stop)] = { $value: ramp[stop], $type: "color" };
      }
      entries.DEFAULT = { $value: swatch.hex, $type: "color" };
      group[name] = {
        $type: "color",
        $description: `Role: ${swatch.role} · ${(swatch.share * 100).toFixed(1)}% coverage`,
        ...entries,
      };
    } else {
      group[name] = {
        $value: swatch.hex,
        $type: "color",
        $description: `Role: ${swatch.role} · ${(swatch.share * 100).toFixed(1)}% coverage`,
      };
    }
  }

  return JSON.stringify({ color: group }, null, 2);
}

/* -------------------------------------------------------------- shadcn --- */

/**
 * A drop-in `globals.css` block for shadcn/ui: semantic tokens for light and
 * dark, every text/surface pair contrast-repaired to AA.
 */
export function toShadcn(palette: Palette, options: EmitOptions = {}): string {
  const { header = true } = options;
  const theme = deriveTheme(palette, options.theme);

  const block = (vars: Record<string, string>, indent = "  ") =>
    Object.entries(vars)
      .map(([k, v]) => `${indent}${k}: ${v};`)
      .join("\n");

  const lines: string[] = [];
  if (header) {
    lines.push(`/* ${HEADER} */`);
    lines.push("/* Paste into app/globals.css, below the Tailwind import. */");
    lines.push("");
  }

  lines.push(":root {", block(theme.light), "}", "");
  lines.push(".dark {", block(theme.dark), "}", "");
  lines.push("@theme inline {");
  for (const key of Object.keys(theme.light)) {
    if (key === "--radius") continue;
    lines.push(`  --color-${key.slice(2)}: var(${key});`);
  }
  lines.push("}");

  return lines.join("\n");
}

/* ----------------------------------------------------------------- svg --- */

/** A shareable palette card. Handy for READMEs, PRs and social posts. */
export function toSVG(palette: Palette, options: EmitOptions = {}): string {
  const swatches = palette.swatches;
  const width = 880;
  const height = 260;
  const gap = 12;
  const pad = 24;
  const cardW = (width - pad * 2 - gap * (swatches.length - 1)) / Math.max(1, swatches.length);

  const cards = swatches
    .map((swatch, i) => {
      const x = pad + i * (cardW + gap);
      const label = swatch.hex.toUpperCase();
      return `  <g>
    <rect x="${x.toFixed(1)}" y="${pad}" width="${cardW.toFixed(1)}" height="140" rx="10" fill="${swatch.hex}"/>
    <text x="${(x + 12).toFixed(1)}" y="${pad + 26}" font-family="ui-monospace, monospace" font-size="11" fill="${swatch.on}" opacity="0.85">${swatch.role}</text>
    <text x="${(x + cardW / 2).toFixed(1)}" y="196" text-anchor="middle" font-family="ui-monospace, monospace" font-size="13" font-weight="600" fill="#e8eaf0">${label}</text>
    <text x="${(x + cardW / 2).toFixed(1)}" y="214" text-anchor="middle" font-family="ui-monospace, monospace" font-size="10" fill="#7c8598">${(swatch.share * 100).toFixed(1)}%</text>
  </g>`;
    })
    .join("\n");

  return `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" role="img" aria-label="Colour palette">
  <rect width="${width}" height="${height}" rx="14" fill="#0e1015"/>
${cards}
  <text x="${pad}" y="${height - 18}" font-family="ui-monospace, monospace" font-size="10" fill="#4b5364" letter-spacing="1.4">PALETTE FORGE</text>
</svg>`;
}

/* --------------------------------------------------------------- utils --- */

/** The 50 to 950 ramp a swatch expands into. */
function rampFor(swatch: Swatch): ToneScale {
  return scale(swatch.hex);
}

/** Valid bare JS identifiers stay unquoted; the rest get quoted. */
function quoteKey(key: string): string {
  return /^[A-Za-z_$][\w$]*$/.test(key) ? key : JSON.stringify(key);
}

/** Every emitter, keyed by format name. */
export const emitters: Record<TokenFormat, (p: Palette, o?: EmitOptions) => string> = {
  css: toCSS,
  tailwind: toTailwind,
  scss: toSCSS,
  ts: toTypeScript,
  js: toJavaScript,
  json: toJSON,
  dtcg: toDTCG,
  shadcn: toShadcn,
  svg: toSVG,
};

/** File extension conventionally used for each format. */
export const extensions: Record<TokenFormat, string> = {
  css: "css",
  tailwind: "css",
  scss: "scss",
  ts: "ts",
  js: "js",
  json: "json",
  dtcg: "json",
  shadcn: "css",
  svg: "svg",
};

/** Emit `palette` in `format`. Throws on an unknown format. */
export function emit(palette: Palette, format: TokenFormat, options: EmitOptions = {}): string {
  const emitter = emitters[format];
  if (!emitter) {
    throw new TypeError(
      `Unknown format ${JSON.stringify(format)}. Expected one of: ${Object.keys(emitters).join(", ")}`,
    );
  }
  return emitter(palette, options);
}
